version: "3.8"

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    env_file:
      - .env
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      INFLUXDB_DB: "fueljournal"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_USER}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_PASSWORD}"
      INFLUXDB_TOKEN: "${INFLUXDB_TOKEN}"
      INFLUXDB_ORG: "${INFLUXDB_ORG}"
    networks:
      - traefik

  website-fueljournal:
    container_name: website-fueljournal
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fueljournal.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.fueljournal.entrypoints=websecure"
      - "traefik.http.routers.fueljournal.tls=true"
      - "traefik.http.services.fueljournal.loadbalancer.server.port=80"
      - "traefik.http.routers.fueljournal.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}

networks:
  traefik:
    external: true

volumes:
  influxdb_data:
