{
 "title": "Fuel Price Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gasoline prices over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fuel prices",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diesel\" or r[\"_field\"] == \"dieselPremium\" or r[\"_field\"] == \"sp95\" or r[\"_field\"] == \"sp98\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Current diesel price for a full tank",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "60-liter of diesel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diesel\")\r\n  |> last()  // Récupère la dernière valeur\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value * 60.0 \r\n  }))\r\n  |> yield(name: \"total_cost\")\r\n"
    }
   ]
  },
  {
   "title": "Real life cost of 60-liter of diesel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diesel\")\r\n  |> last()  // Récupère la dernière valeur\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value * 48.80\r\n  }))\r\n  |> yield(name: \"total_cost\")\r\n"
    }
   ]
  },
  {
   "title": "Diesel price per Liter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diesel\")\r\n  |> last()  // Récupère la dernière valeur\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value\r\n  }))\r\n  |> yield(name: \"total_cost\")\r\n"
    }
   ]
  },
  {
   "title": "Real life cost of 60-liter of diesel premium",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dieselPremium\")\r\n  |> last()  // Récupère la dernière valeur\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value * 48.80\r\n  }))\r\n  |> yield(name: \"total_cost\")\r\n"
    }
   ]
  },
  {
   "title": "60-liter of diesel premium",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dieselPremium\")\r\n  |> last()  // Récupère la dernière valeur\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value * 60.0 \r\n  }))\r\n  |> yield(name: \"total_cost\")\r\n"
    }
   ]
  },
  {
   "title": "Diesel Premium price per Liter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fueljournal\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fuel_prices\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dieselPremium\")\r\n  |> last()  // Récupère la dernière valeur\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value\r\n  }))\r\n  |> yield(name: \"total_cost\")\r\n"
    }
   ]
  }
 ]
}