services:
  glitchandbooks:
    path: "~/services/websites/GlitchAndBooks/"
    db: "postgres"
    container: "db-glitchandbooks"
    user: "ericp"
    password: "PASSWORD"

  asireadandwrite-wp:
    path: "~/services/wordpress/AsIReadAndWrite/"
    db: "mysql"
    container: "db-asireadandwrite"
    user: "root"
    password: "PASSWORD"

  kairos-bot:
    path: "~/services/bot/Kairos-Bot-Reminder/"
    db: "mysql"
    container: "mysql-kairos"
    user: "root"
    password: "PASSWORD"

  cril-bot:
    path: "~/services/bot/Cril-Bot-main/"
    db: "postgres"
    container: "postgres"
    user: "ericp"
    password: "PASSWORD"

max_backups: 5

