global:
  scrape_interval: 60s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node_exporter'
  static_configs:
  - targets: ['192.168.1.140:9100']

- job_name: 'pve'
  static_configs:
  - targets: ['192.168.1.140']
  metrics_path: /pve
  params:
    module: [default]
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: 'pve-exporter:9221'

- job_name: 'tapo'
  static_configs:
  - targets: ['tapo:9333']
