version: "3.8"

volumes:
  prometheus-data: {}
  grafana-data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "80:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    ports:
      - "9221:9221"
    restart: unless-stopped
    volumes:
      - ./config/pve/pve.yml:/etc/prometheus/pve.yml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tapo:
    image: povilasid/p110-exporter
    container_name: tapo
    depends_on:
      - prometheus
    volumes:
      - ./config/tapo/tapo.yml:/app/tapo.yaml
    ports:
      - "9333:9333"
    environment:
      - TAPO_EMAIL=${TAPO_EMAIL}
      - TAPO_PASSWORD=${TAPO_PASSWORD}
      - PORT=${TAPO_PORT}
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
