version: "3.8"

volumes:
  prometheus-data: {}
  grafana-data: {}

services:
  infra-portainer_agent:
    image: portainer/agent:2.19.5
    container_name: infra-portainer_agent
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - proxy

  infra-traefik:
    image: traefik:v3.1
    container_name: infra-traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik/traefik.yml:/traefik.yml:ro
      - ./conf/certs:/certs:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.project.local`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  proxy:
    driver: bridge
